### ISSUE TITLE
自定义封面样式 / 说明封面文件的地址

### ISSUE THREAD

**Issue by delick** [latexstudio/ChinaThesis#3]
**如何自定义封面样式？**
每个学校的封面要求都不一致，是否可以自定义？自定义的内容比如：

- 校徽：更换校徽图形，或者删除校徽
- 增加分类号、保密等级信息
- 增加研究方向等信息

**增加文档中封面文件名及其位置**
如果不支持的话，应该去更改哪个文件？

chinathesis 使用说明中有写中文封面的实现代码，可是究竟是在哪个文件中文档里并没有说明。

**Comment by zepinglee** [comment]
> 如果不支持的话，应该去更改哪个文件？

需要修改 `.dtx` 文件；目前还没写介绍这部分的文档。

这个项目主要是面向其他学校的模板开发者的，由于各个学校的格式差异很大，要求开发者有阅读、修改 dtx 的能力，所以不提供“自定义”的接口。

另外我最近不太赞成 LaTeX 传统的 dtx 文件的方式，直接在 cls 中写注释应该更合适。
