### ISSUE TITLE
'\str_if_eq_x:nnTF' deprecated on，如何解决？

### ISSUE THREAD

**Issue by sikouhjw** [latexstudio/ChinaThesis#4]
## 检查
- [x] 已经阅读学校的论文格式规范
- [x] 已经将模板升级到了最新版
- [x] 已经阅读使用本模板的说明文档
- [ ] 已经阅读常见问题

## 编译环境
- 编译的系统：Windows 10
- TeX 发行版：TeX Live 2019
- 相关宏包版本：ctex v2.4.16
- 模板类型： doctor | master | bachelor

## 描述问题
最新版 TeXLive2019，编译 `main.tex` 失败，`.log` 文件如下
[main.log](https://github.com/latexstudio/ChinaThesis/files/4430591/main.log)
错误应该是这几行
```tex
./chinathesis.cls:75: Undefined control sequence.
<argument> \LaTeX3 error: 
                           '\str_if_eq_x:nnTF' deprecated on 2020-01-01. Use...
```
不懂 latex3，如何解决？

**Comment by muzimuzhi** [comment]
换用 `\str_if_eq:eeTF`。可以在 `texdoc source3` 里查到。

**Comment by sikouhjw** [comment]
> 
> 
> 换用 `\str_if_eq:eeTF`。可以在 `texdoc source3` 里查到。

可以了，感谢

**Comment by zhiyuanzhai** [comment]
考虑在git仓库里面解决一下？

**Comment by zepinglee** [comment]
> 考虑在git仓库里面解决一下？

早已解决了

**Comment by zhiyuanzhai** [comment]
但是我刚刚clone下来的仓库还是出现了这个错误：
```bash
make
```
```log
... ... ... ...

./chinathesis.cls:75: Undefined control sequence.
<argument> \LaTeX3 error:
                           '\str_if_eq_x:nnTF' deprecated on 2020-01-01. Use...
l.75 \ustc@strifeq
                  {\ustc@fontset}{fandol}{
No pages of output.
Transcript written on main.log.
=== TeX engine is 'XeTeX'
Latexmk: Log file says no output from latex
Latexmk: For rule 'xelatex', no output was made
Latexmk: Errors, so I did not complete making targets
Collected error summary (may duplicate other messages):
  xelatex: Command for 'xelatex' gave return code 1
      Refer to 'main.log' for details
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs, or warnings treated as errors.
make: *** [main.pdf] Error 12
```

**Comment by zhiyuanzhai** [comment]
@zepinglee 您指的可能是ustclug那边解决掉了，但是latexstudio这边应该确实没有……

**Comment by muzimuzhi** [comment]
https://github.com/latexstudio/ChinaThesis/blob/4ace040ed5608bdbc66238e0f33173fef89e3f9e/chinathesis.cls#L73

```diff
diff --git a/chinathesis.cls b/chinathesis.cls
index fba888d..3fdd395 100644
--- a/chinathesis.cls
+++ b/chinathesis.cls
@@ -70,7 +70,7 @@
 \fi
 \RequirePackage{natbib}
 \RequirePackage{notoccite}
-\newcommand\ustc@strifeq{\csname str_if_eq_x:nnTF\endcsname}
+\newcommand\ustc@strifeq{\csname str_if_eq:eeTF\endcsname}
 \newcommand\ustc@fontset{\csname g__ctex_fontset_tl\endcsname}
 \ustc@strifeq{\ustc@fontset}{fandol}{
   \setmainfont[
```

**Comment by zepinglee** [comment]
啊，我记错了。这个命令是 2020-01-01 过期的，见 [l3obsolete.txt#L460](https://github.com/latex3/latex3/blob/b7c6bbc86f85c9ebadfe05d3ada8efe595a167fd/l3kernel/doc/l3obsolete.txt#L460)，ustcthesis 的修复见 https://github.com/ustctug/ustcthesis/issues/241 。

使用 `\str_if_eq:eeTF` 虽然可以解决，但是该命令在 2018-06-18 才引入，而模板是向后兼容到 TeX Live 2017 的。所以这样混用 latex2e 和 latex3 还是不太好，最好改成纯 latex2e 的方式。

**Comment by muzimuzhi** [comment]
判断一下 latex format 的时间就行？
